#Select your preferred language to show the messages
#es - español
#en - english
#fr - français
#gr - Deutsch
#ch - 中文
#jp - 日本語
#ru - русский
#pt - português
lang: "es"

#Set percent of player sleeping to pass night (integer)
percent: 50

#Do you want to show in message percent or amount of players
#percent -> "There are 33% of players sleeping, it needs at least 50%"
#amount -> "There are 3 players sleeping, it needs at least 5"
show: "percent"